.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/1.bug-report.yml, .github/ISSUE_TEMPLATE/2.documentation-issue.yml, .github/ISSUE_TEMPLATE/3.feature-request.yml, .github/ISSUE_TEMPLATE/4.question.yml, .github/workflows/docs-deployment.yaml, .ncurc.json, .vuestorefrontcloud/docker/docs/Dockerfile, .vuestorefrontcloud/docker/docs/build-docker.sh, docs/.vuepress/config.js, package.json
=> chore: updated standardization documents

packages/api-client/src/types/types.ts, packages/composables/__tests__/getters/categoryHelpers.spec.ts, packages/composables/src/getters/categoryGetters.ts, packages/composables/src/types/types.ts, packages/theme/components/AppHeader.vue
Small refactor of category getters logic.
=> refactor: category getters

packages/api-client/__tests__/api/addToCart.spec.ts, packages/api-client/src/api/addToCart/addItemToOrderMutation.ts, packages/api-client/src/api/addToCart/index.ts, packages/api-client/src/api/index.ts, packages/api-client/src/fragments/cart.ts, packages/api-client/src/fragments/index.ts, packages/api-client/src/types/API.ts, packages/api-client/src/types/types.ts, packages/composables/__tests__/useCart/useCart.spec.ts, packages/composables/src/composables/useCart/index.ts
=> feat: add product to order

packages/api-client/__tests__/api/getCart.spec.ts, packages/api-client/src/api/getCart/activeOrderQuery.ts, packages/api-client/src/api/getCart/index.ts, packages/api-client/src/api/index.ts, packages/api-client/src/types/API.ts, packages/composables/__tests__/useCart/useCart.spec.ts, packages/composables/src/composables/useCart/index.ts
=> feat: get cart

README.md, docs/composables/use-cart.md, docs/guide/configuration.md, packages/api-client/__tests__/api/setPaymentMethod.spec.ts, packages/api-client/src/api/getProduct/productQuery.ts, packages/api-client/src/api/setPaymentMethod/index.ts, packages/api-client/src/types/API.ts, packages/api-client/src/types/types.ts, packages/composables/__tests__/__mocks__/mockedCart.ts, packages/composables/__tests__/getters/facetHelpers.spec.ts, packages/composables/__tests__/useCart/useCart.spec.ts, packages/composables/src/composables/useCart/index.ts, packages/composables/src/getters/cartGetters.ts, packages/composables/src/getters/facetGetters.ts, packages/composables/src/getters/productGetters.ts, packages/theme/components/Checkout/CartPreview.vue, packages/theme/composables/useUiHelpers/index.ts, packages/theme/helpers/constants.ts, packages/theme/helpers/index.ts, packages/theme/helpers/product.ts, packages/theme/pages/Category.vue, packages/theme/pages/Checkout/Customer.vue, packages/theme/pages/Checkout/Payment.vue, packages/theme/pages/Product.vue
=> feat: mvp flow

docs/changelog/1.0.0-beta.2.md, packages/theme/nuxt.config.js
=> fix: #43 (theme) revert extend and styles

docs/changelog/1.0.0-beta.2.md, docs/guide/getting-started.md
=> docs: #70 update getting started docs

.gitignore, api-extractor.base.json, docs/.vuepress/config.js, docs/changelog/1.0.0-beta.2.md, docs/package.json, docs/typedoc.json, docs/yarn.lock, packages/api-client/api-extractor.json, packages/composables/api-extractor.json
=> docs: #45/api reference

docs/changelog/1.0.0-beta.2.md, docs/package.json, docs/yarn.lock, packages/theme/package.json, yarn.lock
=> chore: #85/update deps

.github/workflows/docs-deployment.yaml, .vuestorefrontcloud/docker/docs/Dockerfile, .vuestorefrontcloud/docker/docs/build-docker.sh
=> chore: release 1.0.0-beta.2 docs

docs/.vuepress/config.js, docs/changelog/1.0.0-beta.4.md, docs/composables/use-related-products.md, packages/api-client/__tests__/api/getRelatedProducts.spec.ts, packages/api-client/src/api/getRelatedProducts/getRelatedProductsQuery.ts, packages/api-client/src/api/getRelatedProducts/index.ts, packages/api-client/src/api/index.ts, packages/api-client/src/types/API.ts, packages/composables/__tests__/useRelatedProducts/useRelatedProducts.spec.ts, packages/composables/src/composables/useRelatedProducts/index.ts, packages/composables/src/factories/index.ts, packages/composables/src/factories/useRelatedProducts.ts, packages/composables/src/index.ts, packages/theme/components/RelatedProducts.vue, packages/theme/pages/Product.vue
=> feat: #37/related products

docs/changelog/1.0.0-beta.4.md, packages/api-client/src/api/getActiveCustomer/activeCustomerQuery.ts, packages/composables/__tests__/__mocks__/mockedOrders.ts, packages/composables/__tests__/getters/orderHelpers.spec.ts, packages/composables/src/getters/orderGetters.ts
=> fix: order history does not display order content 

docs/changelog/1.0.0-beta.4.md, packages/composables/src/composables/useCart/index.ts, packages/theme/components/Checkout/CartPreview.vue, packages/theme/pages/Checkout/Shipping.vue
=> fix: #132 coupon

packages/theme/composables/useUiHelpers/index.ts
=> fix: sort options fixed

docs/changelog/1.0.0-beta.4.md, packages/theme/pages/Category.vue
=> fix: filter checkbox cannot be unchecked 

docs/changelog/1.0.0-beta.4.md, packages/theme/pages/Product.vue
Add v-html in product page to display formatted text properly.
#122
=> fix: add v-html to parse product description on pdp

docs/changelog/1.0.1.md, packages/theme/pages/Category.vue
=> fix: filter display as numeric index in mobile mode

docs/changelog/1.0.1.md, packages/theme/components/MyAccount/ProfileUpdateForm.vue
=> (fix) Customer name not displayed in account form on first load

docs/changelog/1.1.0.md, packages/api-client/src/api/getFacet/searchQuery.ts, packages/composables/src/getters/productGetters.ts, packages/composables/src/types/types.ts, packages/theme/components/AppHeader.vue, packages/theme/components/SearchResults.vue
=>  feat: implement Search functionality for SearchBar

docs/changelog/1.1.0.md, packages/theme/pages/Category.vue
Fix adding and removing products to wishlist on the Category page on desktop and mobile and in horizontal view. 
Closes #169
=> fix: adding/removing product to/from wishlist on Category page

README.md, docs/changelog/1.2.0.md, docs/guide/configuration.md, packages/api-client/README.md, packages/composables/README.md, packages/theme/README.md
=> docs: update redame and docs

docs/changelog/1.2.0.md, packages/api-client/package.json, packages/composables/package.json, packages/composables/src/getters/checkoutGetters.ts, yarn.lock
=> fix: removed ts in checkout getters

docs/changelog/1.2.0.md, packages/theme/pages/Home.vue
=> [Feature]: Replace mocked products in carousel on Home page

docs/changelog/1.2.0.md, packages/theme/composables/useUiHelpers/index.ts
Added skip property to skip products from the previous pages in query
Closes #200 
To be able to use pagination.
- [ X] Bug fix (non-breaking change which fixes an issue)
- [X ] My code follows the code style of this project.
- [ X] I have read the **CONTRIBUTING** document.
- [ X] All new and existing tests passed.
=> fix: fix pagination issue

docs/changelog/1.2.0.md, packages/api-client/src/api/resetPassword/index.ts
=> fix: #205 reset-password params issue

docs/changelog/1.2.0.md, packages/theme/components/Checkout/VsfPaymentProvider.vue, packages/theme/components/Checkout/VsfShippingProvider.vue
Fix shipping/payment providers' descriptions
Closes #212
=> fix: add shipping description and render as html

docs/.vuepress/config.js
=> docs: update changelog

docs/integrations/stripe.md
Provided code example for the integration of Stripe with VSF and Vendure
=> fix: Update the Stripe integration with code examples
